# this_file: .github/workflows/build.yml

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Build
      run: make build
    
    - name: Run tests
      run: make test
    
    - name: Test binary
      run: |
        ./macdefaultbrowser
        ./macdefaultbrowser --help || true