# this_file: .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
    
    - name: Import Code Signing Certificate
      if: ${{ secrets.CODESIGN_CERTIFICATE != '' }}
      env:
        CODESIGN_CERTIFICATE: ${{ secrets.CODESIGN_CERTIFICATE }}
        CODESIGN_PASSWORD: ${{ secrets.CODESIGN_PASSWORD }}
      run: |
        # Create temporary keychain
        security create-keychain -p actions temp.keychain
        security default-keychain -s temp.keychain
        security unlock-keychain -p actions temp.keychain
        
        # Import certificate
        echo "$CODESIGN_CERTIFICATE" | base64 --decode > certificate.p12
        security import certificate.p12 -k temp.keychain -P "$CODESIGN_PASSWORD" -T /usr/bin/codesign -T /usr/bin/productsign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k actions temp.keychain
        
        # Clean up certificate file
        rm certificate.p12
    
    - name: Build distribution package
      env:
        CODESIGN_IDENTITY: ${{ secrets.CODESIGN_IDENTITY }}
      run: VERSION=${{ steps.version.outputs.VERSION }} make dist
    
    - name: Notarize distribution
      if: ${{ secrets.APPLE_ID != '' }}
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        NOTARIZATION_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}
      run: |
        # Notarize the PKG file
        echo "Notarizing PKG..."
        xcrun notarytool submit dist/macdefaultbrowser-${{ steps.version.outputs.VERSION }}.pkg \
          --apple-id "$APPLE_ID" \
          --team-id "$TEAM_ID" \
          --password "$NOTARIZATION_PASSWORD" \
          --wait
        
        # Staple the ticket to the PKG
        echo "Stapling ticket to PKG..."
        xcrun stapler staple dist/macdefaultbrowser-${{ steps.version.outputs.VERSION }}.pkg
        
        # Recreate DMG with stapled PKG
        echo "Recreating DMG with notarized PKG..."
        rm -f dist/macdefaultbrowser-${{ steps.version.outputs.VERSION }}.dmg
        mkdir -p dist/dmg
        cp dist/macdefaultbrowser-${{ steps.version.outputs.VERSION }}.pkg dist/dmg/
        hdiutil create -volname "macdefaultbrowser ${{ steps.version.outputs.VERSION }}" \
          -srcfolder dist/dmg \
          -ov -format UDZO \
          dist/macdefaultbrowser-${{ steps.version.outputs.VERSION }}.dmg
        rm -rf dist/dmg
    
    - name: Cleanup keychain
      if: always() && ${{ secrets.CODESIGN_CERTIFICATE != '' }}
      run: |
        security delete-keychain temp.keychain || true
    
    - name: Create release directory
      run: mkdir -p release
    
    - name: Copy distribution files
      run: |
        cp dist/macdefaultbrowser-${{ steps.version.outputs.VERSION }}.dmg release/
        cp dist/macdefaultbrowser-${{ steps.version.outputs.VERSION }}.pkg release/
        # Also create tar.gz and zip for backward compatibility
        cp build/macdefaultbrowser release/
        cd release
        tar -czf macdefaultbrowser-${GITHUB_REF_NAME}.tar.gz macdefaultbrowser
        zip macdefaultbrowser-${GITHUB_REF_NAME}.zip macdefaultbrowser
        rm macdefaultbrowser
    
    - name: Generate checksums
      run: |
        cd release
        shasum -a 256 macdefaultbrowser-${{ steps.version.outputs.VERSION }}.dmg > macdefaultbrowser-${{ steps.version.outputs.VERSION }}.dmg.sha256
        shasum -a 256 macdefaultbrowser-${{ steps.version.outputs.VERSION }}.pkg > macdefaultbrowser-${{ steps.version.outputs.VERSION }}.pkg.sha256
        shasum -a 256 macdefaultbrowser-${GITHUB_REF_NAME}.tar.gz > macdefaultbrowser-${GITHUB_REF_NAME}.tar.gz.sha256
        shasum -a 256 macdefaultbrowser-${GITHUB_REF_NAME}.zip > macdefaultbrowser-${GITHUB_REF_NAME}.zip.sha256
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    
    - name: Upload tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/macdefaultbrowser-${{ github.ref_name }}.tar.gz
        asset_name: macdefaultbrowser-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/macdefaultbrowser-${{ github.ref_name }}.zip
        asset_name: macdefaultbrowser-${{ github.ref_name }}.zip
        asset_content_type: application/zip
    
    - name: Upload tar.gz checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/macdefaultbrowser-${{ github.ref_name }}.tar.gz.sha256
        asset_name: macdefaultbrowser-${{ github.ref_name }}.tar.gz.sha256
        asset_content_type: text/plain
    
    - name: Upload zip checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/macdefaultbrowser-${{ github.ref_name }}.zip.sha256
        asset_name: macdefaultbrowser-${{ github.ref_name }}.zip.sha256
        asset_content_type: text/plain
    
    - name: Upload DMG
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/macdefaultbrowser-${{ steps.version.outputs.VERSION }}.dmg
        asset_name: macdefaultbrowser-${{ steps.version.outputs.VERSION }}.dmg
        asset_content_type: application/x-apple-diskimage
    
    - name: Upload PKG
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/macdefaultbrowser-${{ steps.version.outputs.VERSION }}.pkg
        asset_name: macdefaultbrowser-${{ steps.version.outputs.VERSION }}.pkg
        asset_content_type: application/x-newton-compatible-pkg
    
    - name: Upload DMG checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/macdefaultbrowser-${{ steps.version.outputs.VERSION }}.dmg.sha256
        asset_name: macdefaultbrowser-${{ steps.version.outputs.VERSION }}.dmg.sha256
        asset_content_type: text/plain
    
    - name: Upload PKG checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/macdefaultbrowser-${{ steps.version.outputs.VERSION }}.pkg.sha256
        asset_name: macdefaultbrowser-${{ steps.version.outputs.VERSION }}.pkg.sha256
        asset_content_type: text/plain